name: build docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}

jobs:
  build_amd64:
    runs-on: buildjet-4vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/login-action@v2
        with:
          username: mohemohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: mohemohe/mastoguard:latest

  build_arm64:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/login-action@v2
        with:
          username: mohemohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: mohemohe/mastoguard:latest-arm64
